### ISSUE TITLE
SchemaLoader doesn't raise error for slots with  both a key and identifier 

### ISSUE THREAD

**Issue by jiaola** [biolink/biolinkml#102]
When parsing a file with slots having both a key and identifier, it needs to raise the value exception catching it. See  https://github.com/biolink/biolinkml/blob/master/tests/test_utils/input/loadererror8.yaml
and https://github.com/biolink/biolinkml/blob/master/tests/test_utils/input/loadererror9.yaml

**Comment by jiaola** [comment]
The testcase is at https://github.com/biolink/biolinkml/blob/master/tests/test_utils/test_schemaloader.py, see function test_key_and_id

**Comment by hsolbrig** [comment]
Note that issue #211 will be dropping "key" from the model completely
