### ISSUE TITLE
test_mappings_rdf is doomed to always fail

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#138]
This always fails for me with the diff:

```
   "@context": [
-     "file:///Users/solbrig/git/biolink/biolinkml/context.jsonld",
?                     ------------------
+     "file:///Users/cjm/repos/biolinkml/context.jsonld",
?                    ++++++++
-     "file:///Users/solbrig/git/biolink/biolinkml/tests/source/meta_mappings.jsonld",
?                     ------------------
+     "file:///Users/cjm/repos/biolinkml/tests/source/meta_mappings.jsonld",
?                    ++++++++
      {
        "@base": "http://example.org/mappings/"
```

This is the source file being comapred:

https://github.com/biolink/biolinkml/blob/16cca2c5bda7c773dd8dd772b572fb113b876b81/tests/source/meta_mappings.json#L147-L148

it's impossible to pass this test unless your username is @hsolbrig !

I will disable for now

**Comment by hsolbrig** [comment]
My username is @hsolbrig -- what's the problem  ;-)

**Comment by hsolbrig** [comment]
Resolved in the latest testing approach.
