### ISSUE TITLE
tests are too fragile

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#140]
I appreciate the rigor of the tests but any time a behavior is changed, it seems it's necessary to update a large number of files.

**Comment by cmungall** [comment]
also: dependence on external services for markdown, 

```
ERROR:MarkdownGenerator:Internal Server Error accessing http://yuml.me/diagram/nofunky;dir:TB/class/[Element]++- examples 0..*>[Example&#124;value:string %3F;description:string %3F]
```

**Comment by cmungall** [comment]
in some cases it appears to work to remove certain directories, things will be regenerated. Sometimes it will take multiple cycles as only one new file will be regenerated per run

test_utils is particularly difficult, as the source yamls are mixed in with the generated files, and it makes multiple cycles to regenerate everything

**Comment by cmungall** [comment]
where do we stand on this @jiaola ?

**Comment by hsolbrig** [comment]
Getting there.  Should have something ready to show by Monday

**Comment by hsolbrig** [comment]
Testing framework has been overhauled.  Documentation still pending

**Comment by hsolbrig** [comment]
Splitting of biolinkml into linkml/linkml-model/linkml-runtime should help with this
