### ISSUE TITLE
Add property to indicate a class is top level

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#177]
currently jsonschemagen takes a command line arg for the top level class, this is used as the root of the json tree

it would be useful to elevate this to being explicit in the model. It would be semantically silent (except for tree serializations like json) but could help with documentation. The top level class would be the entrypoint for a user rather than throwing them at a big list of classes. It could also be the top level uml diagram in index.md

**Comment by jiaola** [comment]
@cmungall  Can you please show us an example of what the jsonschema output should look like? Harold and I are trying to figure out how it is supposed to work but we don't think the --top-class parameter has worked.

**Comment by cmungall** [comment]
You can find examples here:

 - https://github.com/microbiomedata/nmdc-metadata/
 - https://github.com/cmungall/metadata_converter
 - https://github.com/cmungall/sssom-py
 - https://github.com/cmungall/ontology-change-language

**Comment by cmungall** [comment]
Try this:

```
$ gen-json-schema tests/test_issues/input/issue_129.yaml
...
   },
   "properties": {},
   "title": "types",
   "type": "object"
}
```

compared with

```
$ gen-json-schema -t c tests/test_issues/input/issue_129.yaml
...
   },
   "properties": {
      "age_in_years": {
         "type": "integer"
      },
      "children": {
         "items": {
            "type": "string"
         },
         "type": "array"
      },
...
      }
   },
   "title": "types",
   "type": "object"
}

```

**Comment by cmungall** [comment]
looks like test_issue_129 should explicitly test for this

**Comment by jiaola** [comment]
@cmungall  We added a tree_root in class definition slots. See https://github.com/biolink/biolinkml/pull/195

See https://github.com/biolink/biolinkml/blob/master/tests/test_issues/test_issue_177.py for the test. 

It adds the properties to the top level in JSON schema. But it didn't change anything else such as the "title" of the root in JSON. 

Please let us know if other things need to be done.

**Comment by cmungall** [comment]
This is great thanks! Bill, as soon as 1.5.4 comes out we should use this
in nmdc-schema
