### ISSUE TITLE
Consider supporting python 3.6 with backports

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolinkml#19]
For example:

    install_requires=[
        'contextvars;python_version=="3.6"',
        'dataclasses;python_version=="3.6"'
    ]

**Comment by hsolbrig** [comment]
General question:  How big an issue is this?  The reason I ask is that I suspect that this isn't the only 3.6/3.7 issue.  We muck around with the typing library output a bit and it didn't become stable until the 3.7 release.

**Comment by kshefchek** [comment]
It's a non issue, and I think I under estimated the complexity of the code here (assumed it was just dataclasses).  I'll close!
