### ISSUE TITLE
Need a way to test warning messages from logger

### ISSUE THREAD

**Issue by jiaola** [biolink/biolinkml#190]
See test_schemaloader.py.test_basic_merge to see the pattern

It needs to be put into test_issue_177.py

**Comment by hsolbrig** [comment]
Submitted as part of https://github.com/biolink/biolinkml/pull/191 -- see: https://github.com/biolink/biolinkml/blob/issue_18/tests/test_issues/test_issue_18.py#L41  (or, once merged) https://github.com/biolink/biolinkml/blob/master/tests/test_issues/test_issue_18.py#L41
