### ISSUE TITLE
biolink:id requirement

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#2]
The current ShEx model requires bl:id:

`:s1 bl:id ":s1".`

This should be unnecessary.  We propose (and implement) in this model that converters to Neo4J add:
`:se bl:name "foo"; bl:x ... .` --> `:id :se`

**Comment by hsolbrig** [comment]
Is this still an issue?  If so, any chance we can get a bit more clarification?

**Comment by cmungall** [comment]
I guess I initiated this?

If I understand the problem, it was that in bl, we state

```
  named thing:
    description: "a databased entity or concept/class"
    slots:
      - id
      - name
      - category
```

and this was previously generating a fake shex constraint

I don't quite understand the proposed solution of where neo4j comes in...

...but it seems this is no longer an issue. I don't see this in the ShEx. I think it should be the case that identifier types are always treated as the node iri
