### ISSUE TITLE
gen-py-classes generating extra slot info

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolinkml#228]
For reference see https://github.com/microbiomedata/nmdc-metadata/pull/139.

When running `gen-py-classes` on `nmdc.yaml`, we are getting extra slots of the form `<x value>_has_raw value`, `<y value>_has_unit`. For example:
```
slots.quantity_value_has_raw_value = Slot(uri=NMDC.has_raw_value, name="quantity value_has raw value", curie=NMDC.curie('has_raw_value'),
                      model_uri=NMDC.quantity_value_has_raw_value, domain=QuantityValue, range=Optional[str])
slots.quantity_value_has_unit = Slot(uri=NMDC.has_unit, name="quantity value_has unit", curie=NMDC.curie('has_unit'),
                      model_uri=NMDC.quantity_value_has_unit, domain=QuantityValue, range=Optional[str])
```
Is this behavior correct?

cc @cmungall @deepakunni3

**Comment by cmungall** [comment]
We may be able to close this in favor of the more general #231 

it's not clear the existing python behavior is so bad. we don't have an easy mechanism for compound keys here, hence the manifestation of the induced primary key

**Comment by wdduncan** [comment]
Yes. Let's close in favor of #231.
