### ISSUE TITLE
Document which pypi products need to be used when

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#31]
There is some confusion about the different libraries and when to use them cc @kshefchek @deepakunni3 @justaddcoffee

@RichardBruskiewich asks about biolinkMG here #28 and @hsolbrig states this is replaced by biolinkml

We also appear to lack a pypi module for the biolink-model datamodel.py - this would be useful to have.

I think most developers will not need biolinkml or biolinkMG. I believe previously people had been using this to parse the biolink-model YAML into objects and then operate on those, for example, for use as a vocabulary when writing code to generate blmod compliant triples.

In fact I think if we just release biolink-model datamodel.py it will solve everyone's problems. The object model will be introspectable, and we can also add static methods, see #21

**Comment by cmungall** [comment]
For example, for the code @justaddcoffee is writing to embed biolink types in dipper code

```
import biolinkmodel.datamodel as bl

...

def foo:
  ..
  add_category(obj, bl.Gene)
  ...

def add_category(obj, cls):
   tgt_iri = 'https://web3id.org/biolink/vocab/' + cls.__name__
   ...
```

**Comment by hsolbrig** [comment]
We are proposing a rename, so the code above would become:

```python
import biolink.model as bl

def foo():
      add_category(obj, bl.Gene)

def add_category(obj,  cls):
      tgt_iri = 'https://web3id.org/biolink/vocab/' + cls.__name__
```

And, after a second tweak, where we will add the class IRI as a static element:

```python
def add_category(obj, cls):
     tgt_iri = cls.iri
```

**Comment by hsolbrig** [comment]
@deepakunni3 will be creating a new PYPI module, which will consist solely (or mostly) of biolink.model

**Comment by cmungall** [comment]
can this be closed?

**Comment by deepakunni3** [comment]
Yes
