### ISSUE TITLE
Generate a mapping table

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#35]
For the paper, would be useful to have a python pandas dataframe that has a biolink model element for each row, with each column being a separate schema/model/ontology/research, and the value being whether the mapping is exact or inexact

**Comment by deepakunni3** [comment]
We still do not differentiate between mappings as being exact or inexact. 

Earlier discussions concluded at separating the mappings into one of the following
- exact_matches
- broader_matches
- narrower_matches
- lose_matches

If this is already supported by Biolinkml then we should edit the Biolink Model YAML to use these slots.

Full discussion here: https://github.com/biolink/biolink-model/pull/173

**Comment by wdduncan** [comment]
Hi Deepak. Do you still need this table? I can't recall ... Sorry.

**Comment by cmungall** [comment]
let's

**Comment by wdduncan** [comment]
@cmungall Did you mean "let us generate the table?"
