### ISSUE TITLE
Implement a biolink model tagger, to add categories to nodes in a set of triples

### ISSUE THREAD

**Issue by cmungall** [biolink/biolinkml#36]
Scenario:

We have a triplestore or a collection of ttl files. These are not explicitly biolink compliant. However, they do utilize some kind of ontology that is mapped to biolink-model. For example, this could be monarch triples, go-cam triples, bio2rdf, wikidata. Or just a plain OWL file from OBO. The nodes may be either instances or classes.

We want to run code such that every node will be tagged `N blmod:category blmod:<Class>`, where the Class is obtained via `rdf:type{0,1}/rdfs:subClassOf*` to an upper ontology class that is mapped to biolink-model category `Class`. v2 of the code can also tag associations, but for now we focus just on named entities.

There are a few different ways to address this.

 1. procedural code that loads the ttl (and associated tbox) into memory, loads biolink-model, performs traversal, cacheing as necessary, and adds tags
 2. As part of the build, we generate a mega SPARQL CONSTRUCT that can be executed on the ttl
     - a: do this using the SPARQL `VALUES` construct
     - b: have the mappings in biolink-model loaded as triples (e.g. skos:exactMatch) and do something like `CONSTRUCT {?n blmod:cat ?c} WHERE {?n rdf:type{0,1}/rdfs:subClassOf*/skos:exactMatch ?c . strStarts(?c, iri(blmod:))}`

Although 2 seems more declarative the idea of having a piece of SPARQL generated each build seems a bit fiddly. Also IMO sometimes hard to predict performance of SPARQL. This needs to be guaranteed to scale to large triplestores.

1 seems a bit more predictable, but at the same time I hate putting more procedural code into the world.

Thoughts @balhoff @goodb @kshefchek @TomConlin @deepakunni3 @justaddcoffee @vemonet?

**Comment by justaddcoffee** [comment]
@cmungall Seems very useful though to have a general tool to add biolink categories to existing TTLs/triplestores in a post hoc way, and probably would go a long way toward encouraging adoption of the biolink model. 

Might it be better for me to help develop this general tool instead of [doing this for this specific set of TTLs](https://github.com/monarch-initiative/dipper/pull/746)? Glad to help with either or both though.

**Comment by goodb** [comment]
@cmungall Stepping back up a level here.  The need for this typing (in my work on GO-CAM at least) really arises from 2 problems: (1) reasoning over large ontologies can be slow, so dynamic instance typing with a reasoner isn't always an option and (2) many developers either don't know how to use reasoners or can not access them in the context they are working in (e.g. javascript working in the client with a fragment of an instance graph).  So, the point of all of this boils down to precomputing inferences as much as possible and distributing this information in as a convenient a form as possible for the general audience of developers.  The most convenient form and the most broadly applicable that I can think of is a map of (ontology term):(biolink type).  

What about building out the map of all biolinkable ontology terms and distributing that as a simple text file?

Such a file could be easily consumed in any programming language without any dependency and would serve the purpose of the biolink tagger.  

This puts the onus on the ontology maintainers to contribute the mapping file for the ontology.  And those are the right people to do this work.

**Comment by cmungall** [comment]
> What about building out the map of all biolinkable ontology terms and distributing that as a simple text file?

Ideally we would have this for all of OBO but this may be hard.

For example, if I wanted to make a table for all of OBO I could in theory just download all ontologies or query ontobee to make the table. Unfortunately the default distribution of many ontologies lack subClassOf axioms that link to higher level classes. This is partly what the OBO core project is about

A more pragmatic alternative is to do this at the level of integrative "importer" ontologies such as go-lego and monarch.owl. The maintainers of these have usually taken steps to plug gaps and add bridge axioms so that everything has a path up to an appropriate grouping.

If we were doing this, is there any need for a text file? We may as well inject the triples back into the ontology.

**Comment by goodb** [comment]
> If we were doing this, is there any need for a text file? We may as well inject the triples back into the ontology.

It pains me to say this, but I think that yes, there probably is.  In the same way people like to grab the external2go xref tables rather than pulling them directly out of the ontologies, many people will prefer to read in yet another tsv to get to the tagging information.  In cases where the ontology in question is large enough to be slow to work with (e.g. neo and even goplus), it actually makes a lot of sense to separate out this table.

**Comment by kshefchek** [comment]
Would the dipper categorizer be of interest here? https://github.com/monarch-initiative/dipper/tree/master/scripts/categories
