### ISSUE TITLE
question: where are the default contexts defined?

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolinkml#5]
Many files state:
```yaml
default_curi_maps:
 - obo_context
 - monarch_context
 - idot_context
 - semweb_context
```
But where are these contexts defined and what they include. This search could not find a [definition of semweb_context](https://github.com/search?p=3&q=org%3Abiolink+semweb_context&type=Code)

**Comment by hsolbrig** [comment]
These maps use https://github.com/prefixcommons/prefixcommons-py


see: https://github.com/prefixcommons/biocontext/tree/master/registry  for the individual contexts
