### ISSUE TITLE
domain for slot is set after first use

### ISSUE THREAD

**Issue by simonjupp** [biolink/biolinkml#50]
When loading the following I get an error about the domain being set for the slot `ValueError: File: None Slot: id domain (test class 1) does not match declaring class "(test class 2)"`.  It would be useful if the domain is not set by default. 

```
id: http://example.com

classes:

    test class 1:
      slots:
        - id

    test class 2:
      slots:
        - id

slots:
    id:
        description: a identifier
        identifier: true
```

**Comment by deepakunni3** [comment]
@hsolbrig Thoughts?

**Comment by hsolbrig** [comment]
At the moment every slot has a unique domain.  I'm not saying that this is right, but is how the modeling language works today.  If you want to use the same slot name in two or more classes, the options are:

A common base class:

````
id: http://example.com

classes:
    base class:
       slots:
          -id
    
    test class 1:
       is_a: base class

    test class 2:
       is_a: base class

slots:
    id:
        description: a identifier
        identifier: true
```

Using slot aliases:
```
id: http://example.com

classes:

    test class 1:
      slots:
        - test class 1 id

    test class 2:
      slots:
        - test class 2 id

slots:
    test class 1 idi:
        description: a identifier
        identifier: true
        alias: id

    test class 2 idi:
        description: a identifier
        identifier: true
        alias: id
```

Before we proceed, I'll post a description of how biolinkml slots align with UML properties and associations.

**Comment by hsolbrig** [comment]
See: https://github.com/biolink/biolinkml/blob/master/UML.md

**Comment by cmungall** [comment]
@hsolbrig I don't think we want the current behavior.

To be more specific, I think that having a single domain is fine. What is wrong is that the slot declaration induces a domain declaration. It shouldn't do this!

We went around this a few times, I thought we had all this resolved. Maybe this is a ghost of the old behavior?

**Comment by cmungall** [comment]
See https://github.com/biolink/biolink-model/issues/198

**Comment by hsolbrig** [comment]
https://github.com/biolink/biolink-model/issues/198 has been resolved (at least as I understood it -- could still be missing the boat.)  That resolution is actually what I was trying to explain in a rather long-winded way in the UML response above. You can declare a domain for a slot or  (`slot.domain`) the slot for a domain (`class.slots`) the first asserts that all instances of the predicate reference the target domain:
```python
for subj, obj in g.predicates(slot_instance):
    assert isinstance(subj, domain)
    assert isinstance(obj, range)  
```
The second *further* asserts that all instances of the class may/must have the slot:
```python
for pred, obj in g.predicate_objects(class_instance):
   assert isinstance(pred, slot)
   assert isianstace(obj, range)
```
Currently, a `class.slots` assertion entails an equivalent `slot.domain`assertion.

(Note: you can also declare both, but, if you do, they must match -- this is the error @simonjupp indirectly triggered above)

The issue above (as I understand it) is that @simonjupp is either attempting to :
1) declare that the domain of the slot named "id" is the *union* of `test class 1` and `test class 2` -or-
2) there are two different slots, both named id, one of whose domain is `test class 1` and the second is `test class 2`.

The common base class is how use 1) is currently addressed and aliases are how use 2) is addressed.   I can't think of another use scenario -- if you wanted "domainless slots" in the current model, you would accomplish this be defining a common base class say, `thing` and a slot named "id" whose domain was `thing`.  If you wanted to assert that class A has a slot of type string named `id` and class B also has a slot of type string named `id`, you would use the alias model:
```
classes:
    A:
      slots:
          - a_id
    B:
       slots:
          - b_id

slots:
     a_id:
       alias: id
       range: string

     b_id:
       alias: id
       range: string    <--- note that this doesn't have to be the same range
```

If you wanted two *different*, both named "id", one whose domain was "A" and the second whose domain was "B", where "A" and "B" were unaware of these slots, you would:
```
slots:
     a_id:
        domain: A
        range: string
        alias: id

     b_id:
        domain: B
        range: string
        alias: id
```

I think we've got two related issues on our hands:
1) We really need to document the crap out of the language, to make sure that everyone understands and (more importantly) we all agree that this is what is wanted
2) In places, like the above, where confusion may arise, we need to add some "syntactic sugar" to allow people to work with idioms they may be more familiar without introducing ambiguity.

Footnotes:

1) The fundamental issue here is that UML-like models, which we are most familiar with, `always` use slot aliases.  Declaring that the class "Person" has an attribute named "id" and the class "School" has an attribute named "id" declares two *completely different* Property/Association tuples and, in the context of biolinkml, two different slots.  This seems natural until you ask, "What is the name (URI) of the `Person.id` slot?", which brings you to one of the big stumbling blocks when it comes to UML to RDF mapping.  You have to come up with an arbitrary rule, where you use path notation `(model:<Class>_<attribute>)` or extend the model to include predicate maps (person.id.url = foaf:name).  As we sort of kind of live in the RDF world, we have to address these issues up front.

2) We do *not* want to make the mistake that the UML community made early on in their development process, where they decided to prioritize readability and "intuitiveness" over non-ambiguity.  This decision made perfect sense when it came to using UML as a modeling language -- it is in no small part why they were successful.  This decision, however, absolutely killed them when it came to using the very same UML as a meta-modeling language, where a number of ambiguities and under-specifications made at the heart of the model prevented them from exchanging models between UML tools.

**Comment by cmungall** [comment]
@hsolbrig I believe that after the last comment here we had a long discussion about this while I was at the Hackathon and we came up with a path forward...?

**Comment by cmungall** [comment]
We also came up with this doc:

https://docs.google.com/document/d/1ZNE7C1ZKO0go9NIX6KG5eybvdgJzxwhW6tkzhNY2wOM/edit
