### ISSUE TITLE
Namespaces in Python should include the curie prefix

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#68]
Currently, the generated Python emits namespaces in the form:

`BFO = Namespace('http://purl.obolibrary.org/obo/BFO_')`

This doesn't identify the preferred curie prefix.   Proposed a wrapper solution in the form:

`BFO = CurieNamespace('bfo', 'http://purl.obbolibrary.org/obo/BFO_')` that behaves exactly like Namespace with one more method:

`def curie(localname: Optional[str] = None) -> str:`

Which returns:
* `BFO.curie()` --> 'bfo:'
* `BFO.curie('12345') --> 'bfo:12345'

**Comment by RichardBruskiewich** [comment]
Hi @hsolbrig, just noticed that you assigned this to me, but I get the impression that your code already made the change, so I guess this is your way of notifying me of the change (so that I can use in my code?) Let me know if there is something else to do here.

**Comment by cmungall** [comment]
Looks like this is done
