### ISSUE TITLE
Model CEDAR templates

### ISSUE THREAD

**Issue by wdduncan** [biolink/biolinkml#82]
@cmungall Since we are exploring using CEDAR templates in NMDC, it could be useful to model these templates in biolinkml.

See issue https://github.com/GenomicsStandardsConsortium/mixs-ng/issues/6#issuecomment-564607528

**Comment by cmungall** [comment]
CEDAR templates are modeled as JSON-Schema docs. So I would first have a jsonschema->blml (we obviously have the reverse), with extensions for handling the CEDAR extensions

**Comment by cmungall** [comment]
Subsumed by #273
