### ISSUE TITLE
Issue with induced domains

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolinkml#84]
Issue with the induced domains.  (reported by @cmungall )

i.e. I have declared an 'id' slot, which is fairly generic. But when I declare it for one class, I can't use it in another:

ValueError: File: /Users/cjm/repos/nmdc-metadata/schema/nmdc.yaml Slot: id domain (biosample) does not match declaring class "(characteristic)"
make: *** [nmdc.py] Error 1

I can get around this by declaring a named entity superclass... but this isn't satisfactory...

**Comment by cmungall** [comment]
This is the same as #50

**Comment by hsolbrig** [comment]
Yes - somehow #50 never got pushed.  Have the fix cached here and will get it in as soon as I resolve some merge issues.  Apologies for the poor git hygiene

**Comment by cmungall** [comment]
Thanks

**Comment by aj95b** [comment]
I am just starting to get to know the Biolink modelling language-- I was going over the installation notes and have been trying to execute the sample example/organization.yaml. I am getting the same error: 
ValueError: File: /home/arpita/examples/organization.yaml Slot: id domain (organization) does not match declaring class "(employee)"
Any insight or direction would be helpful. Thanks!

**Comment by cmungall** [comment]
Hi @aj95b - what version of biolinkml are you using? This should have been fixed some time ago

**Comment by aj95b** [comment]
RDFLib Version: 5.0.0

That's the output of importing biolinkml package from the python shell.

**Comment by cmungall** [comment]
oh, i meant the version of biolinkml!

**Comment by aj95b** [comment]
I'm sorry I wouldn't know how to do that, biolinklml --verison (and biolinkml -V) gives me ModuleNotFoundError for the apt_pkg module and when I try to install it, even that's not found. If it all it helps, I am attaching the installation result (screenshot) of 
pipenv install biolinkml
![biolink](https://user-images.githubusercontent.com/14183174/89685848-c21a9b00-d8c2-11ea-9f01-c12a4a1c8beb.png)

**Comment by aj95b** [comment]
Okay, I couldn't find biolink/model.py, but taking cues form the ValueError messages, this is what I could find:
cd ~/.local/share/virtualenvs/arpita-TuPfZhwW/lib/python3.6/site-packages/biolinkml-1.3.8.dist-info$ emacs METADATA 
![biolinkml2](https://user-images.githubusercontent.com/14183174/89739896-0f754480-da4a-11ea-9fd1-07003eb171bd.png)

**Comment by hsolbrig** [comment]
What are you trying to do with biolinkml?

There are a number of scripts that come with the installation.  As an example, if you want to generate python from a biolink compliant model, you could:
```bash
> pipenv run gen-python <model.yaml>
```

model.py is a library that has been generated with gen-python.

You might want to take a peek at https://github.com/biolink/biolink-model for some use cases.  The Makefile shows how things are generated.
